# Report



**The Motivation Behind Our Project**
- For our project, we wanted to explore baseball because it's the most statistically weighted sport and there are years and years of data. It's a commonly used dataset and one that would be useful and easy to explore. There are important questions to be answered by the salary of players. 

**Research Question for Moneyball: Visualizations of Baseball Salaries**
- We want to find the relationship between player performance and salary between different eras of baseball and evaluate how that relationship has changed over long and short periods of time. 

**Background of Data and Relevant Context**
- It's helpful to have a basic comprehension of how the game of baseball has evolved over a 144 year period. Here is a brief summary of the basic changes since MLB’s inception. https://blastmotion.com/blog/evolution-of-sport-baseball/?srsltid=AfmBOooVC-YIx4L9Jc6uylHY6jQFwAok4YbATH4AUn0Qp9lL8C6-U1ji#gref

- Knowledge of the rules of baseball are necessary to understand this data. An explanation of the rules can be found here: https://en.wikipedia.org/wiki/Baseball_rules

- It's also helpful to know the abbreviations for common statistics in baseball: here's a list of relevant ones
teamID Team

lgID League

W Wins

L Losses

G Games

H Hits

ER Earned Runs

HR Homeruns

BB Walks

SO Strikeouts

BAOpp Opponent’s Batting Average

ERA Earned Run Average

IBB Intentional Walks

WP Wild Pitches

HBP Batters Hit By Pitch

BK Balks

BFP Batters faced by Pitcher

GS Games started

GF Games Finished

R Runs Allowed

SH Sacrifices by opposing batters

SF Sacrifice flies by opposing batters

GIDP Grounded into double plays by opposing batter

**Data & Data Insights**

  

-Motivation
-Research Question 
-Background
-Data
-Data Insights
-Conclusions/BPicture
